---
mds_user: mds
mds_user_password: mds
mds_server_url: https://kafka1.confluent.io:8090

rolebindings: []

rbac_current: [] 
# set whitelist as a regex expression e.g. "cluster1|cluster2|cluster3"
rbac_cluster_whitelist: ".*"
rbac_dump_file: false
rbac_dump_destination: /tmp/rbac_dump_out.yml
rbac_to_add: []
rbac_to_delete: []
rbac_protected_accounts: ""
rbac_delete_enabled: true
scopes_list: []
