---
# connectivity variables
rest_server_url: https://rest.confluent.io:8090
rest_user: user
rest_user_password: user-secret

cacl_dump_file: false
cacl_dump_destination: /tmp/cacl_dump_out.yml
cacls: []

# global variables
cacl_list: []
acl_to_add: []
acl_to_delete: []